# Generated by Django 4.2.6 on 2023-10-16 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0003_alter_student_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="curator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group",
                to="group.teacher",
            ),
        ),
    ]
