# Generated by Django 4.2.6 on 2023-10-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0004_student_phone_alter_group_curator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_path", models.CharField(max_length=50)),
                ("log_method", models.CharField(max_length=50)),
                ("execution_time", models.CharField(max_length=50)),
            ],
        ),
    ]
